### ISSUE TITLE
aarch64:pkgsrc/misc/mate-utils build failed

### ISSUE THREAD

**Issue by ebijun** [ebijun/NetBSD#119]
GEN    crh/
Traceback (most recent call last):
  File "/usr/pkg/bin/itstool", line 1598, in <module>
    doc.merge_translations(translations, opts.lang, strict=opts.strict)
  File "/usr/pkg/bin/itstool", line 986, in merge_translations
    lcnode.setProp(attr, origlang)
  File "/usr/pkg/lib/python2.7/site-packages/libxml2.py", line 3590, in setProp
    if ret is None:raise treeError('xmlSetProp() failed')
libxml2.treeError: xmlSetProp() failed

**Comment by bjjl** [comment]
Found a solution for this? Same problem here...

**Comment by egnappahz** [comment]
This really is a cool bug. I have to go to the source dir and clean it out and then it works.
Since this is still not fixed after a year, This really is itstool having some major cleaning issues. Though they seem to be blaming python for it.
